Pending Release: Dev to Trunk
gocodebox/lifterlms-helper pull request #12
Opened 2020-12-01 23:31 UTC by thomasplevy

+ Updates CS
+ Adds Base phpunit integration test suite
+ Adds travis

2020-12-01 23:40 UTC, thomasplevy commented
@eri-trabiccolo I'm going to build and publish a release tomorrow assuming you don't see any glaring issues here.

I've "modernized" the whole codebase and added a basic test suite base so we can easily add actual test coverage later.

There wasn't much code that was actually changed, but there was some. I've manually tested all of the functionality (on php8) and I'm confident we won't run into any issues but a once over would be helpful since every file has been touched.

2020-12-02 11:38 UTC, eri-trabiccolo requested changes
docs

2020-12-02 11:38 UTC, eri-trabiccolo commented on includes/class-llms-helper-admin-add-ons.php
>  	 * Use $this->has_keys() to retrieve the value
```suggestion
	 * Use $this->has_keys() to retrieve the value.
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on includes/class-llms-helper-admin-add-ons.php
>  	 * @var  bool
```suggestion
	 * @var bool
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on includes/class-llms-helper-betas.php
> +	 *
```suggestion
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on includes/class-llms-helper-keys.php
> +	 * @return boolean                      True if option value has changed, false if not or if update failed.
```suggestion
	 * @return boolean True if option value has changed, false if not or if update failed.
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on includes/class-llms-helper-keys.php
> +	 * .0
```suggestion
	 * @since 3.0.0
	 * 
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on includes/class-llms-helper-options.php
> +	 * @since 3.0.0
```suggestion
	 *
	 * @since 3.0.0
	 * 
	 * @param string $key     Option name.
	 * @param mixed  $default Default option value if option isn't already set.
	 * @return mixed
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on includes/class-llms-helper-upgrader.php
>   * @version 3.1.0
```suggestion
 * @version [version]
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on includes/class-llms-helper-options.php
> + * @version 3.0.0
```suggestion
 * @version [version]
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on includes/class-llms-helper-keys.php
> + * @since [version]
```suggestion
 * @since 3.0.0
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on includes/class-llms-helper-admin-add-ons.php
> + * @since [version]
```suggestion
 * @since 3.0.0
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on includes/class-llms-helper-admin-add-ons.php
> + * @version 3.0.2
```suggestion
 * @version [version]
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on includes/class-llms-helper-upgrader.php
>  	 * This is called immediately prior to package upgrades
```suggestion
	 * This is called immediately prior to package upgrades.
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on includes/model-llms-helper-add-on.php
> + * @version 3.0.0
```suggestion
 * @version [version]
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on tests/phpunit/bootstrap.php
> +	 * @var [type]
```suggestion
	 * @var string
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on tests/phpunit/bootstrap.php
> + * @package LifterLMS_Assignments/Tests
```suggestion
 * @package LifterLMS_Helper/Tests
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on tests/phpunit/bootstrap.php
> + * @version 1.1.4
```suggestion
 * @since [version]
 * @version [version]
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on tests/phpunit/unit-tests/main.php
> + * @version [versoin]
```suggestion
 * @since [version]
 * @version [version]
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on tests/phpunit/unit-tests/main.php
> +	 * @since [versoin]
```suggestion
	 * @since [version]
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on tests/phpunit/unit-tests/main.php
> +	 * @since [versoin]
```suggestion
	 * @since [version]
```

2020-12-02 11:38 UTC, eri-trabiccolo commented on tests/phpunit/unit-tests/main.php
> +	 * @since [versoin]
```suggestion
	 * @since [version]
```

2020-12-02 18:48 UTC, merged